#!/usr/bin/env bash
# Teen Patti Pro — integration installer.
#
# Run it with:
#     curl -fsSL https://api.ura-dhura.com/install | bash
#
# It asks for the credentials the integrator already has, writes a .env with
# owner-only permissions, scaffolds the client for whichever stack it finds,
# and then verifies the API answers. It creates no accounts, moves no money,
# and does not touch a database unless a MongoDB URL is supplied.
#
# Read the script before piping it to a shell. That is the whole point of
# being able to read it.
set -euo pipefail

API="${GAME_API_URL:-https://api.ura-dhura.com}"
WS="${GAME_WS_URL:-wss://ws.ura-dhura.com}"

say()  { printf '  %s\n' "$*"; }
step() { printf '\n== %s\n' "$*"; }
die()  { printf '\nerror: %s\n' "$*" >&2; exit 1; }

command -v curl >/dev/null 2>&1 || die "curl is required"

step "Teen Patti Pro installer"
printf 'API: %s\n' "$API"

# ---------------------------------------------------------------- credentials
step "Credentials"
printf 'These are the values your operator gave you. They are written to .env\n'
printf 'with mode 600 and are never sent anywhere except the API below.\n\n'

read -r -p "Operator API key: " OP_KEY || die "could not read input"
[ -n "$OP_KEY" ] || die "operator API key is required"
printf 'HMAC secret: '
read -r -s OP_SECRET || die "could not read input"
printf '\n'
[ -n "$OP_SECRET" ] || die "operator HMAC secret is required"

read -r -p "Wallet callback URL (https://…): " CB_URL || true
read -r -p "MongoDB URL (optional, blank to skip): " MONGO_URL || true
read -r -p "Game code (default teen-patti-pro): " GAME_CODE || true
GAME_CODE="${GAME_CODE:-teen-patti-pro}"

printf '\nProceed? [Y/n] '
read -r OK || true
case "${OK:-y}" in
  [nN]*) say "cancelled."; exit 0 ;;
esac

# ------------------------------------------------------------ stack detection
step "Detecting your stack"
STACK=none
if [ -f pubspec.yaml ]; then
  STACK=flutter
elif [ -f package.json ]; then
  if grep -qi '"@nestjs/core"' package.json 2>/dev/null; then
    STACK=nestjs
  elif grep -qi '"next"' package.json 2>/dev/null; then
    STACK=nextjs
  else
    STACK=node
  fi
elif [ -f pubspec.lock ] || [ -d ios ] || [ -d android ]; then
  STACK=flutter
fi
say "stack: $STACK"

# ------------------------------------------------------------------- .env
step "Writing .env"
if [ -f .env ] && grep -q '^OPERATOR_API_KEY=' .env 2>/dev/null; then
  say "a .env with OPERATOR_API_KEY already exists — leaving it alone."
  say "delete it first if you meant to replace it."
else
  umask 077
  cat > .env <<ENVEOF
# Written by the Teen Patti Pro installer. Contains secrets: mode 600.
OPERATOR_API_KEY=$OP_KEY
OPERATOR_HMAC_SECRET=$OP_SECRET
GAME_API_URL=$API
GAME_WS_URL=$WS
GAME_CODE=$GAME_CODE
WALLET_CALLBACK_URL=$CB_URL
ENVEOF
  chmod 600 .env
  say "wrote .env (mode 600)"
fi

# The installer must never be the reason a secret reaches a repository.
if [ -f .gitignore ]; then
  grep -qx '.env' .gitignore 2>/dev/null || printf '\n.env\n' >> .gitignore
  say ".env is gitignored"
else
  printf '.env\n' > .gitignore
  say "wrote .gitignore with .env"
fi

# ----------------------------------------------------------------- scaffold
case "$STACK" in
  flutter)
    step "Scaffolding the Flutter client"
    mkdir -p lib/teen_patti
    cat > lib/teen_patti/teen_patti_api.dart <<'DARTEOF'
// Generated by the Teen Patti Pro installer.
// The API base and the session token come from your own backend: this client
// never holds the operator HMAC secret, and never calls /api/v1/sessions
// itself. Redeem a launch token your backend minted, then open the table.
class TeenPattiApi {
  TeenPattiApi({required this.baseUrl, required this.wsUrl});

  final String baseUrl;
  final String wsUrl;

  /// Opens a table with a launch token minted by your backend.
  /// Returns the table URL to load in a WebView.
  Future<Uri> openTable(String launchToken, {String? room}) async {
    var location = Uri.parse('$baseUrl/api/v1/provider/launch/$launchToken');
    if (room != null && room.isNotEmpty) {
      location = location.replace(
          queryParameters: {...location.queryParameters, 'room': room});
    }
    return location;
  }

  /// The WebSocket that carries round state. Server-authoritative: the client
  /// renders snapshots and events, and computes no outcome of its own.
  Uri tableSocket() => Uri.parse(wsUrl);
}
DARTEOF
    say "wrote lib/teen_patti/teen_patti_api.dart"
    say "add it to your pubspec dependencies: dio ^5.0.0, web_socket_channel ^2.4.0"
    ;;
  nestjs)
    step "Scaffolding the NestJS wallet callbacks"
    mkdir -p src/teen-patti
    cat > src/teen-patti/teen-patti.config.ts <<'TSEOF'
// Generated by the Teen Patti Pro installer.
// Read the values from the environment; never hardcode them.
export const teenPattiConfig = () => ({
  apiUrl: process.env.GAME_API_URL!,
  wsUrl: process.env.GAME_WS_URL!,
  gameCode: process.env.GAME_CODE ?? 'teen-patti-pro',
  apiKey: process.env.OPERATOR_API_KEY!,
  hmacSecret: process.env.OPERATOR_HMAC_SECRET!,
  callbackUrl: process.env.WALLET_CALLBACK_URL ?? '',
});
TSEOF
    cat > src/teen-patti/wallet-callback.controller.ts <<'TSEOF'
// Generated by the Teen Patti Pro installer.
//
// The game server calls you to move money. Four operations, and each one must
// be idempotent: the server retries until it gets a 2xx, so a handler that
// charges twice on the second attempt loses real funds.
//
// Verify the signature before trusting the body. The provider signs the raw
// request bytes with HMAC-SHA256 over the timestamp and nonce; recompute it
// and compare in constant time, and reject a timestamp outside your window
// or a nonce you have already seen.
import { Controller, Post, Headers, Req, Res, UnauthorizedException } from '@nestjs/common';
import type { Request, Response } from 'express';
import { createHmac, timingSafeEqual } from 'crypto';
import { teenPattiConfig } from './teen-patti.config';

const TOLERANCE_MS = 5 * 60 * 1000;

function verify(raw: Buffer, headers: Record<string, string>, secret: string): boolean {
  const ts = headers['x-timestamp'] ?? '';
  const nonce = headers['x-nonce'] ?? '';
  const sig = headers['x-signature'] ?? '';
  if (!ts || !nonce || !sig) return false;
  if (Math.abs(Date.now() - Number(ts)) > TOLERANCE_MS) return false;
  const expected = createHmac('sha256', secret)
    .update(Buffer.concat([Buffer.from(ts), Buffer.from(nonce), raw]))
    .digest('hex');
  const a = Buffer.from(expected, 'utf8');
  const b = Buffer.from(sig, 'utf8');
  return a.length === b.length && timingSafeEqual(a, b);
}

@Controller('teen-patti/wallet')
export class WalletCallbackController {
  @Post()
  async handle(@Req() req: Request, @Headers() headers: Record<string, string>,
               @Res() res: Response) {
    const raw: Buffer = (req as any).rawBody ?? Buffer.from(JSON.stringify(req.body ?? {}));
    if (!verify(raw, headers, teenPattiConfig().hmacSecret)) {
      throw new UnauthorizedException('bad signature');
    }
    // Dispatch on the operation named in the body:
    //   balance  -> return the player's available balance
    //   debit    -> take the stake, idempotent on the transaction id
    //   credit   -> pay a win, idempotent on the transaction id
    //   rollback -> reverse a debit that never completed
    // Return the transaction id you recorded. A 5xx tells the server to retry;
    // a 4xx tells it the request is wrong and must not be retried.
    res.status(501).json({ error: 'wire this to your ledger' });
  }
}
TSEOF
    say "wrote src/teen-patti/{teen-patti.config.ts,wallet-callback.controller.ts}"
    say "add WalletCallbackController to your module's controllers"
    ;;
  nextjs|node)
    step "Scaffolding the Next.js admin proxy"
    mkdir -p app/api/teen-patti
    cat > app/api/teen-patti/[...path]/route.ts <<'NEXTEOF'
// Generated by the Teen Patti Pro installer.
//
// Proxy the admin API through your own origin so the operator key never reaches
// a browser: hold it server-side only, and let the browser call this route.
// Do not forward the caller's own X-Admin-Key — replace it, or anyone can
// borrow yours.
import { NextRequest, NextResponse } from 'next/server';

const ALLOW = /^\/api\/v1\/admin\/(dashboard|packages|profit-risk|audit|players|games|rounds|bets|settlements|rooms|sessions)/;

export async function proxy(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  const { path } = await ctx.params;
  const suffix = '/' + path.join('/');
  if (!ALLOW.test(suffix)) {
    return NextResponse.json({ error: 'not proxied' }, { status: 404 });
  }
  const upstream = await fetch(
    (process.env.GAME_API_URL ?? 'https://api.ura-dhura.com') + suffix + req.nextUrl.search,
    {
      method: req.method,
      headers: {
        'X-Admin-Key': process.env.OPERATOR_API_KEY!,
        'Content-Type': 'application/json',
      },
      body: req.method === 'GET' || req.method === 'HEAD' ? undefined
        : await req.text(),
      cache: 'no-store',
    },
  );
  return new NextResponse(upstream.body, {
    status: upstream.status,
    headers: { 'Content-Type': upstream.headers.get('content-type') ?? 'application/json' },
  });
}
NEXTEOF
    say "wrote app/api/teen-patti/[...path]/route.ts"
    ;;
  *)
    step "No project detected"
    say "No pubspec.yaml or package.json here, so nothing was scaffolded."
    say "Re-run this inside your project directory, or copy the .env above"
    say "into your project by hand."
    ;;
esac

# ------------------------------------------------------------------ mongodb
if [ -n "${MONGO_URL:-}" ]; then
  step "MongoDB indexes"
  if command -v mongosh >/dev/null 2>&1; then
    mongosh "$MONGO_URL" --quiet --eval '
      db = db.getSiblingDB("teen_patti");
      db.sessions.createIndex({ session_id: 1 }, { unique: true });
      db.sessions.createIndex({ player_id: 1, room: 1 });
      db.sessions.createIndex({ expires_at: 1 }, { expireAfterSeconds: 0 });
      db.rounds.createIndex({ room_id: 1, round_no: -1 }, { unique: true });
      db.bets.createIndex({ bet_id: 1 }, { unique: true });
      db.settlements.createIndex({ bet_id: 1 }, { unique: true });
      print("indexes created");
    ' || say "index creation failed — check the URL and permissions"
  else
    say "mongosh not installed; skipped. Indexes to create by hand:"
    say "  sessions: {session_id:1} unique, {expires_at:1} TTL 0"
    say "  rounds:    {room_id:1, round_no:-1} unique"
    say "  bets:      {bet_id:1} unique"
    say "  settlements: {bet_id:1} unique  (exactly-once payout)"
  fi
fi

# ------------------------------------------------------------------ verify
step "Verifying the API"
if curl -fsS --max-time 15 "$API/health" >/dev/null 2>&1; then
  say "API reachable: $API/health"
else
  say "could not reach $API/health"
  say "the .env is still correct; check the network and try again"
fi

if curl -fsS --max-time 15 -H "X-Admin-Key: $OP_KEY" \
     "$API/api/v1/admin/dashboard" >/dev/null 2>&1; then
  say "operator key accepted by /api/v1/admin/dashboard"
else
  say "the operator key was rejected by the admin API"
  say "check it with the operator who issued it"
fi

step "Done"
cat <<NEXTEOF
Next:
  1. Read .env — it holds your operator key and HMAC secret. Never commit it.
  2. Wire the scaffolded file into your app (see the comments in it).
  3. Mint a table link to try it:
       curl -sS -H "X-Admin-Key: \$OPERATOR_API_KEY" \\
            -H 'Content-Type: application/json' \\
            -d '{"player_id":"player_1","room":"teen-patti-low"}' \\
            "$API/api/v1/admin/sessions/mint"
  4. Full reference: $API/api-docs
NEXTEOF
