#!/usr/bin/env bash
# Teen Patti Pro — integration installer.
#
# Run it with:
#     curl -fsSL https://api.ura-dhura.com/install | bash
#
# It asks for the credentials the integrator already has, writes a .env with
# owner-only permissions, scaffolds the client for whichever stack it finds,
# and then verifies the API answers. It creates no accounts, moves no money,
# and does not touch a database unless a MongoDB URL is supplied.
#
# Read the script before piping it to a shell. That is the whole point of
# being able to read it.
set -euo pipefail

API="${GAME_API_URL:-https://api.ura-dhura.com}"
WS="${GAME_WS_URL:-wss://ws.ura-dhura.com}"

say()  { printf '  %s\n' "$*"; }
step() { printf '\n== %s\n' "$*"; }
die()  { printf '\nerror: %s\n' "$*" >&2; exit 1; }

command -v curl >/dev/null 2>&1 || die "curl is required"

step "Teen Patti Pro installer"
printf 'API: %s\n' "$API"

# ---------------------------------------------------------------- credentials
step "Credentials"
printf 'These are the values your operator gave you. They are written to .env\n'
printf 'with mode 600 and are never sent anywhere except the API below.\n\n'

read -r -p "Operator API key: " OP_KEY || die "could not read input"
[ -n "$OP_KEY" ] || die "operator API key is required"
printf 'HMAC secret: '
read -r -s OP_SECRET || die "could not read input"
printf '\n'
[ -n "$OP_SECRET" ] || die "operator HMAC secret is required"

read -r -p "Wallet callback URL (https://…): " CB_URL || true
read -r -p "MongoDB URL (optional, blank to skip): " MONGO_URL || true
read -r -p "Game code (default teen-patti-pro): " GAME_CODE || true
GAME_CODE="${GAME_CODE:-teen-patti-pro}"

printf '\nProceed? [Y/n] '
read -r OK || true
case "${OK:-y}" in
  [nN]*) say "cancelled."; exit 0 ;;
esac

# ------------------------------------------------------------ stack detection
step "Detecting your stack"
STACK=none
if [ -f pubspec.yaml ]; then
  STACK=flutter
elif [ -f package.json ]; then
  if grep -qi '"@nestjs/core"' package.json 2>/dev/null; then
    STACK=nestjs
  elif grep -qi '"next"' package.json 2>/dev/null; then
    STACK=nextjs
  else
    STACK=node
  fi
elif [ -f pubspec.lock ] || [ -d ios ] || [ -d android ]; then
  STACK=flutter
fi
say "stack: $STACK"

# ------------------------------------------------------------------- .env
step "Writing .env"
if [ -f .env ] && grep -q '^OPERATOR_API_KEY=' .env 2>/dev/null; then
  say "a .env with OPERATOR_API_KEY already exists — leaving it alone."
  say "delete it first if you meant to replace it."
else
  umask 077
  cat > .env <<ENVEOF
# Written by the Teen Patti Pro installer. Contains secrets: mode 600.
OPERATOR_API_KEY=$OP_KEY
OPERATOR_HMAC_SECRET=$OP_SECRET
GAME_API_URL=$API
GAME_WS_URL=$WS
GAME_CODE=$GAME_CODE
WALLET_CALLBACK_URL=$CB_URL
ENVEOF
  chmod 600 .env
  say "wrote .env (mode 600)"
fi

# The installer must never be the reason a secret reaches a repository.
if [ -f .gitignore ]; then
  grep -qx '.env' .gitignore 2>/dev/null || printf '\n.env\n' >> .gitignore
  say ".env is gitignored"
else
  printf '.env\n' > .gitignore
  say "wrote .gitignore with .env"
fi

# ----------------------------------------------------------------- scaffold
case "$STACK" in
  flutter)
    step "Scaffolding the Flutter client (service, BLoC, WebView)"
    mkdir -p lib/teen_patti
    cat > lib/teen_patti/teen_patti_config.dart <<'DARTEOF'
// Generated by the Teen Patti Pro installer.
class TeenPattiConfig {
  const TeenPattiConfig({
    required this.apiBase,
    required this.wsUrl,
    this.gameCode = 'teen-patti-pro',
  });

  final String apiBase;
  final String wsUrl;
  final String gameCode;

  factory TeenPattiConfig.fromEnvironment(Map<String, String> env) =>
      TeenPattiConfig(
        apiBase: env['GAME_API_URL'] ?? 'https://api.ura-dhura.com',
        wsUrl: env['GAME_WS_URL'] ?? 'wss://ws.ura-dhura.com',
        gameCode: env['GAME_CODE'] ?? 'teen-patti-pro',
      );
}
DARTEOF
    cat > lib/teen_patti/teen_patti_session_service.dart <<'DARTEOF'
// Generated by the Teen Patti Pro installer.
//
// The client never mints its own session and never holds the operator HMAC
// secret. Your backend mints a launch token; this service redeems it. Putting
// the secret in the app would publish it to anyone who unpacks the build.
import 'teen_patti_config.dart';

class TeenPattiSession {
  final String launchToken;
  final String playerId;
  final String room;
  final DateTime expiresAt;
  const TeenPattiSession({
    required this.launchToken,
    required this.playerId,
    required this.room,
    required this.expiresAt,
  });
}

class TeenPattiSessionService {
  TeenPattiSessionService(this.config, {http.Client? client})
      : _client = client ?? http.Client();

  final TeenPattiConfig config;
  final http.Client _client;

  /// Asks YOUR backend for a launch token. Never calls the operator API
  /// directly: that endpoint is HMAC-signed and the secret cannot ship here.
  Future<TeenPattiSession> requestLaunchToken(String playerId,
      {String room = 'teen-patti-low'}) async {
    // POST to your own endpoint, e.g.
    //   POST https://your-backend/api/teen-patti/launch  {player_id, room}
    throw UnimplementedError(
      'Point this at your backend. It mints the token with the operator key; '
      'the app must never see the key or the HMAC secret.');
  }

  /// Opens a table with a token. 302-redirects into the client with the
  /// session attached, so no cookie and no second auth step are involved.
  Uri tableUrl(TeenPattiSession session) =>
      Uri.parse('${config.apiBase}/api/v1/provider/launch/'
          '${session.launchToken}');

  /// The socket that carries round state. The server is authoritative: the
  /// client renders snapshots and events and computes no outcome of its own.
  Uri tableSocket(TeenPattiSession session) => Uri.parse(config.wsUrl);
}
DARTEOF
    cat > lib/teen_patti/teen_patti_round_bloc.dart <<'DARTEOF'
// Generated by the Teen Patti Pro installer.
//
// One event in, one immutable state out. Two things matter more than the
// plumbing: a rejected bet arrives as a socket "error", not as a round event,
// so it needs its own case or a full table reads as a silent no-op; and no
// state here decides an outcome. The server dealt the cards and the server
// says who won.
import 'dart:async';
import 'dart:convert';

import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:web_socket_channel/web_socket_channel.dart';

sealed class TeenPattiEvent {}

class RoundSnapshotReceived extends TeenPattiEvent {
  final Map<String, dynamic> data;
  RoundSnapshotReceived(this.data);
}

class RoundEventReceived extends TeenPattiEvent {
  final String kind;
  final Map<String, dynamic> data;
  RoundEventReceived(this.kind, this.data);
}

class RoundSocketFailed extends TeenPattiEvent {
  final String code;
  RoundSocketFailed(this.code);
}

class RoundConnectionLost extends TeenPattiEvent {
  RoundConnectionLost();
}

enum RoundPhase { idle, connecting, betting, revealed, settled, failed }

class TeenPattiState {
  final RoundPhase phase;
  final Map<String, dynamic>? snapshot;
  final String? lastEventKind;
  final List<String> winners;
  final String? errorCode;

  const TeenPattiState({
    this.phase = RoundPhase.idle,
    this.snapshot,
    this.lastEventKind,
    this.winners = const [],
    this.errorCode,
  });

  int get balance => (snapshot?['balance'] as num?)?.round() ?? 0;
  String get status => (snapshot?['status'] as String?) ?? 'WAITING';
  bool get canBet => phase == RoundPhase.betting && status == 'BETTING_OPEN';

  TeenPattiState copyWith({
    RoundPhase? phase,
    Map<String, dynamic>? snapshot,
    String? lastEventKind,
    List<String>? winners,
    String? errorCode,
  }) =>
      TeenPattiState(
        phase: phase ?? this.phase,
        snapshot: snapshot ?? this.snapshot,
        lastEventKind: lastEventKind ?? this.lastEventKind,
        winners: winners ?? this.winners,
        errorCode: errorCode,
      );
}

class TeenPattiRoundBloc extends Bloc<TeenPattiEvent, TeenPattiState> {
  TeenPattiRoundBloc(WebSocketChannel channel, {required String session})
      : super(const TeenPattiState()) {
    on<RoundSnapshotReceived>((e, emit) {
      final s = e.data['status'] as String? ?? 'WAITING';
      emit(state.copyWith(
        snapshot: e.data,
        phase: _phaseFor(s, state.snapshot),
        errorCode: null,
      ));
    });
    on<RoundEventReceived>((e, emit) {
      // result.declared is when faces may be shown. Before it, the snapshot
      // carries '**' and drawing them would reveal a hand the server has not
      // published.
      if (e.kind == 'result.declared' || e.kind == 'settlement.completed') {
        final w = (e.data['winners'] as List?)?.cast<String>() ?? const [];
        emit(state.copyWith(phase: RoundPhase.settled, winners: w,
                            lastEventKind: e.kind));
      } else {
        emit(state.copyWith(lastEventKind: e.kind));
      }
    });
    on<RoundSocketFailed>((e, emit) =>
        emit(state.copyWith(phase: RoundPhase.failed, errorCode: e.code)));
    on<RoundConnectionLost>((e, emit) =>
        emit(state.copyWith(phase: RoundPhase.connecting)));

    channel.stream.listen(
      (raw) {
        final msg = jsonDecode(raw as String) as Map<String, dynamic>;
        final kind = msg['kind'];
        if (kind == 'snapshot') {
          add(RoundSnapshotReceived(
              (msg['data'] as Map).cast<String, dynamic>()));
        } else if (kind == 'event') {
          final d = (msg['data'] as Map).cast<String, dynamic>();
          add(RoundEventReceived((d['kind'] ?? '') as String, d));
        } else if (kind == 'error') {
          final d = (msg['data'] as Map).cast<String, dynamic>();
          add(RoundSocketFailed((d['code'] ?? 'UNKNOWN') as String));
        }
      },
      onDone: () => add(RoundConnectionLost()),
    );

    channel.sink.add(jsonEncode({'action': 'subscribe', 'session': session}));
  }

  static RoundPhase _phaseFor(String status, Map<String, dynamic>? prev) {
    if (status == 'BETTING_OPEN') return RoundPhase.betting;
    if (status == 'BETTING_CLOSED') return RoundPhase.revealed;
    if (status == 'RESULT' || status == 'SETTLED' || status == 'CLOSED') {
      return RoundPhase.settled;
    }
    return prev == null ? RoundPhase.connecting : RoundPhase.idle;
  }
}
DARTEOF
    cat > lib/teen_patti/teen_patti_webview.dart <<'DARTEOF'
// Generated by the Teen Patti Pro installer.
//
// The game renders in a WebView because the client is canvas-based. That is
// the whole integration: the WebView loads a URL the launch endpoint
// redirects, and the Dart side never touches the canvas. Keep this thin --
// anything you inject here runs alongside the game with the same session.
//
// If you embed voice or video, keep it a separate layer sharing only the room
// name. A player joining that channel must not imply a round event, and a
// round event must never be inferred from it.
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

class TeenPattiWebView extends StatefulWidget {
  const TeenPattiWebView({super.key, required this.tableUrl});
  final Uri tableUrl;

  @override
  State<TeenPattiWebView> createState() => _TeenPattiWebViewState();
}

class _TeenPattiWebViewState extends State<TeenPattiWebView> {
  late final WebViewController _controller;

  @override
  void initState() {
    super.initState();
    _controller = WebViewController()
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      // The client polls nothing from the host app, so leave the decision
      // open rather than granting everything by default.
      ..setNavigationDelegate(NavigationDelegate(
        onNavigationRequest: (request) {
          // Keep the player inside the game: the launch URL 302s once, then
          // the client is served from the same origin.
          return request.url.startsWith('https://') ||
              request.url.startsWith('wss://')
              ? NavigationDecision.navigate
              : NavigationDecision.prevent;
        },
      ))
      ..loadRequest(widget.tableUrl);
  }

  @override
  Widget build(BuildContext context) => WebViewWidget(controller: _controller);
}
DARTEOF
    say "wrote lib/teen_patti/ (config, session service, round BLoC, WebView)"
    say "add to pubspec: flutter_bloc ^8.1.0, web_socket_channel ^2.4.0,"
    say "  webview_flutter ^4.7.0, http ^1.2.0"
    ;;
  nestjs)
    step "Scaffolding the NestJS wallet callbacks"
    mkdir -p src/teen-patti
    cat > src/teen-patti/teen-patti.config.ts <<'TSEOF'
// Generated by the Teen Patti Pro installer.
// Read the values from the environment; never hardcode them.
export const teenPattiConfig = () => ({
  apiUrl: process.env.GAME_API_URL!,
  wsUrl: process.env.GAME_WS_URL!,
  gameCode: process.env.GAME_CODE ?? 'teen-patti-pro',
  apiKey: process.env.OPERATOR_API_KEY!,
  hmacSecret: process.env.OPERATOR_HMAC_SECRET!,
  callbackUrl: process.env.WALLET_CALLBACK_URL ?? '',
});
TSEOF
    cat > src/teen-patti/wallet-callback.controller.ts <<'TSEOF'
// Generated by the Teen Patti Pro installer.
//
// A thin adapter. The rules that matter live in WalletCallbackService and
// IdempotentLedgerService, so they are stated once rather than restated here:
//   - verify the signature on the RAW bytes, before parsing
//   - reject a stale timestamp and a replayed nonce
//   - key the ledger write on the transaction id, not on arrival
//   - answer 4xx for a request that can never succeed as sent, so the server
//     stops retrying it, and 5xx only for a transient fault
import {
  Body,
  Controller,
  Headers,
  HttpCode,
  Post,
  Req,
  Res,
  UnauthorizedException,
  UsePipes,
  ValidationPipe,
} from '@nestjs/common';
import type { Request, Response } from 'express';
import { WalletCallbackDto } from './wallet.dto';
import { WalletCallbackService } from './wallet-callback.service';

@Controller('teen-patti/wallet')
@UsePipes(new ValidationPipe({ transform: true, whitelist: true }))
export class WalletCallbackController {
  constructor(private readonly wallet: WalletCallbackService) {}

  @Post()
  @HttpCode(200)
  async handle(
    @Req() req: Request,
    @Headers() headers: Record<string, string>,
    @Body() dto: WalletCallbackDto,
    @Res() res: Response,
  ) {
    // rawBody must be the exact bytes that were signed. Re-serialising the
    // parsed object changes the key order and the digest no longer matches --
    // which looks like a signature bug and is not one.
    const raw: Buffer =
      (req as any).rawBody ??
      Buffer.from(JSON.stringify(req.body ?? {}));
    try {
      this.wallet.verify(raw, headers);
    } catch (e) {
      throw e instanceof UnauthorizedException
        ? e
        : new UnauthorizedException('bad signature');
    }
    try {
      const out = await this.wallet.handle(dto);
      res.status(200).json({
        balance: out.balance,
        currency: dto.currency ?? 'COIN',
        transaction_id: dto.transactionId,
        replayed: out.replayed,
      });
    } catch (e) {
      // A 5xx tells the server to retry; a 4xx tells it the request is wrong
      // and must not be. Nothing here returns a fake balance: an unconfigured
      // wallet fails loudly rather than answering 0.
      res.status(503).json({ error: 'wallet unavailable' });
      throw e;
    }
  }
}
TSEOF
    cat > src/teen-patti/wallet.dto.ts <<'DTOEOF'
// Generated by the Teen Patti Pro installer.
//
// The four operations the game server calls to move money. The operation is
// named in the body rather than the path, so one signature handler can
// dispatch -- which is also why the discriminator is validated first.
import { IsIn, IsInt, IsOptional, IsString, Min } from 'class-validator';

export const WALLET_OPS = ['balance', 'debit', 'credit', 'rollback'] as const;
export type WalletOp = (typeof WALLET_OPS)[number];

export class WalletCallbackDto {
  @IsIn(WALLET_OPS)
  op!: WalletOp;

  @IsString()
  playerId!: string;

  // The idempotency anchor. Every mutating operation is keyed on this: the
  // server retries until it gets a 2xx, so a handler that charges on arrival
  // rather than on this value charges twice when the first response is lost.
  @IsString()
  transactionId!: string;

  @IsOptional()
  @IsInt()
  @Min(0)
  amount?: number;

  @IsOptional()
  @IsString()
  currency?: string;

  @IsOptional()
  @IsString()
  ref?: string;
}
DTOEOF
    cat > src/teen-patti/ledger.schema.ts <<'SCHEMAEOF'
// Generated by the Teen Patti Pro installer.
//
// The local record of what this service was asked to do, and the reason the
// game server can retry safely. UNIQUE on transaction_id is the constraint
// that makes a duplicate debit or credit impossible; doing it in application
// code leaves a window between the read and the write, and the server will
// find it.
import { BadRequestException, Inject } from '@nestjs/common';

export type LedgerEntry = {
  transactionId: string;
  op: 'balance' | 'debit' | 'credit' | 'rollback';
  playerId: string;
  amount: number;
  currency: string;
  balanceAfter: number;
  createdAt: Date;
};

/** DI token for the store. An interface emits no runtime value, so it cannot
 *  be used as an injection token -- that is a compile error, not a runtime one. */
export const LEDGER_STORE = Symbol('LEDGER_STORE');

export interface LedgerStore {
  findByTransaction(transactionId: string): Promise<LedgerEntry | undefined>;
  /** Must reject a second entry with the same transactionId. */
  record(entry: LedgerEntry): Promise<void>;
  getBalance(playerId: string, currency: string): Promise<number>;
  adjust(
    playerId: string,
    currency: string,
    delta: number,
  ): Promise<number>;
}

/**
 * Wrap a LedgerStore with the idempotency guarantee the protocol requires.
 *
 * Order matters: claim the transaction BEFORE moving money, then commit. If
 * the process dies between the two, the claim is already recorded and the
 * retry replays the stored balance rather than moving money again.
 */
export class IdempotentLedgerService {
  // The token is explicit because the interface has no runtime value for
  // Nest to infer a provider from.
  constructor(
    @Inject(LEDGER_STORE) private readonly store: LedgerStore,
  ) {}

  async apply(
    dto: {
      op: 'balance' | 'debit' | 'credit' | 'rollback';
      playerId: string;
      transactionId: string;
      amount?: number;
      currency?: string;
    },
  ): Promise<{ balance: number; replayed: boolean }> {
    const currency = dto.currency ?? 'COIN';
    const existing = await this.store.findByTransaction(dto.transactionId);
    if (existing) {
      // Replay. Return the balance as it was, not today's -- a retry must not
      // report a different number than the original attempt.
      return { balance: existing.balanceAfter, replayed: true };
    }
    if (dto.op === 'balance') {
      const balance = await this.store.getBalance(dto.playerId, currency);
      await this.store.record({
        transactionId: dto.transactionId,
        op: dto.op,
        playerId: dto.playerId,
        amount: 0,
        currency,
        balanceAfter: balance,
        createdAt: new Date(),
      });
      return { balance, replayed: false };
    }
    const amount = dto.amount ?? 0;
    if (amount <= 0) {
      // 4xx, not 5xx: the server must not retry a request that can never
      // succeed as sent.
      throw new BadRequestException('amount must be positive');
    }
    const delta =
      dto.op === 'debit' ? -amount : dto.op === 'credit' ? amount : 0;
    const balanceAfter = await this.store.adjust(
      dto.playerId,
      currency,
      delta,
    );
    await this.store.record({
      transactionId: dto.transactionId,
      op: dto.op,
      playerId: dto.playerId,
      amount,
      currency,
      balanceAfter,
      createdAt: new Date(),
    });
    return { balance: balanceAfter, replayed: false };
  }
}
SCHEMAEOF
    cat > src/teen-patti/wallet-callback.service.ts <<'SVCEOF'
// Generated by the Teen Patti Pro installer.
//
// Signature verification lives here so the controller stays a thin adapter and
// the rule is stated once. Two checks, both required: recompute the digest and
// compare in constant time, and reject a timestamp outside the window or a
// nonce already seen. Constant-time comparison alone is not enough -- without
// the freshness checks a captured request replays verbatim forever.
import { Injectable, UnauthorizedException } from '@nestjs/common';
import { createHmac, timingSafeEqual } from 'crypto';
import { IdempotentLedgerService } from './ledger.schema';
import { WalletCallbackDto } from './wallet.dto';
import { teenPattiConfig } from './teen-patti.config';

const TOLERANCE_MS = 5 * 60 * 1000;

@Injectable()
export class WalletCallbackService {
  private readonly seenNonces = new Map<string, number>();

  constructor(private readonly ledger: IdempotentLedgerService) {}

  verify(raw: Buffer, headers: Record<string, string | undefined>): void {
    const ts = headers['x-timestamp'] ?? '';
    const nonce = headers['x-nonce'] ?? '';
    const sig = headers['x-signature'] ?? '';
    if (!ts || !nonce || !sig) {
      throw new UnauthorizedException('missing signature headers');
    }
    const at = Number(ts);
    if (!Number.isFinite(at) || Math.abs(Date.now() - at) > TOLERANCE_MS) {
      throw new UnauthorizedException('timestamp outside the tolerance window');
    }
    const seenAt = this.seenNonces.get(nonce);
    if (seenAt !== undefined && Date.now() - seenAt <= TOLERANCE_MS) {
      throw new UnauthorizedException('nonce replay');
    }
    const expected = createHmac(
      'sha256',
      teenPattiConfig().hmacSecret,
    )
      .update(Buffer.concat([Buffer.from(ts), Buffer.from(nonce), raw]))
      .digest('hex');
    const a = Buffer.from(expected, 'utf8');
    const b = Buffer.from(sig, 'utf8');
    if (a.length !== b.length || !timingSafeEqual(a, b)) {
      throw new UnauthorizedException('bad signature');
    }
    this.seenNonces.set(nonce, Date.now());
    if (this.seenNonces.size > 10_000) {
      // Bound the replay cache; entries older than the window are useless.
      const cutoff = Date.now() - TOLERANCE_MS;
      for (const [k, v] of this.seenNonces) {
        if (v < cutoff) this.seenNonces.delete(k);
      }
    }
  }

  async handle(dto: WalletCallbackDto) {
    return this.ledger.apply(dto);
  }
}
SVCEOF
    cat > src/teen-patti/teen-patti.module.ts <<'MODEOF'
// Generated by the Teen Patti Pro installer.
import { Module } from '@nestjs/common';
import { WalletCallbackController } from './wallet-callback.controller';
import { WalletCallbackService } from './wallet-callback.service';
import {
  IdempotentLedgerService,
  LedgerStore,
  LEDGER_STORE,
} from './ledger.schema';

/** Replace with your own store. It must reject a duplicate transactionId. */
class PlaceholderLedgerStore implements LedgerStore {
  private balances = new Map<string, number>();
  private entries = new Map<string, any>();
  async findByTransaction(id: string) { return this.entries.get(id); }
  async record(e: any) {
    if (this.entries.has(e.transactionId)) {
      throw new Error('duplicate transaction id');
    }
    this.entries.set(e.transactionId, e);
  }
  async getBalance(p: string, c: string) { return this.balances.get(p + c) ?? 0; }
  async adjust(p: string, c: string, d: number) {
    const next = (this.balances.get(p + c) ?? 0) + d;
    this.balances.set(p + c, next);
    return next;
  }
}

@Module({
  controllers: [WalletCallbackController],
  providers: [
    WalletCallbackService,
    IdempotentLedgerService,
    { provide: LEDGER_STORE, useClass: PlaceholderLedgerStore },
  ],
})
export class TeenPattiModule {}
MODEOF
    say "wrote src/teen-patti/ (config, dto, ledger schema+service,"
    say "  callback service, callback controller, module)"
    say "replace PlaceholderLedgerStore in teen-patti.module.ts with your own"
    say "  -- it must reject a duplicate transactionId"
    ;;
  nextjs|node)
    step "Scaffolding the Next.js admin proxy"
    mkdir -p app/api/teen-patti
    cat > app/api/teen-patti/[...path]/route.ts <<'NEXTEOF'
// Generated by the Teen Patti Pro installer.
//
// Proxy the admin API through your own origin so the operator key never reaches
// a browser: hold it server-side only, and let the browser call this route.
// Do not forward the caller's own X-Admin-Key — replace it, or anyone can
// borrow yours.
import { NextRequest, NextResponse } from 'next/server';

const ALLOW = /^\/api\/v1\/admin\/(dashboard|packages|profit-risk|audit|players|games|rounds|bets|settlements|rooms|sessions)/;

export async function proxy(req: NextRequest, ctx: { params: Promise<{ path: string[] }> }) {
  const { path } = await ctx.params;
  const suffix = '/' + path.join('/');
  if (!ALLOW.test(suffix)) {
    return NextResponse.json({ error: 'not proxied' }, { status: 404 });
  }
  const upstream = await fetch(
    (process.env.GAME_API_URL ?? 'https://api.ura-dhura.com') + suffix + req.nextUrl.search,
    {
      method: req.method,
      headers: {
        'X-Admin-Key': process.env.OPERATOR_API_KEY!,
        'Content-Type': 'application/json',
      },
      body: req.method === 'GET' || req.method === 'HEAD' ? undefined
        : await req.text(),
      cache: 'no-store',
    },
  );
  return new NextResponse(upstream.body, {
    status: upstream.status,
    headers: { 'Content-Type': upstream.headers.get('content-type') ?? 'application/json' },
  });
}
NEXTEOF
    say "wrote app/api/teen-patti/[...path]/route.ts"
    ;;
  *)
    step "No project detected"
    say "No pubspec.yaml or package.json here, so nothing was scaffolded."
    say "Re-run this inside your project directory, or copy the .env above"
    say "into your project by hand."
    ;;
esac

# ------------------------------------------------------------------ mongodb
if [ -n "${MONGO_URL:-}" ]; then
  step "MongoDB indexes"
  if command -v mongosh >/dev/null 2>&1; then
    mongosh "$MONGO_URL" --quiet --eval '
      db = db.getSiblingDB("teen_patti");
      db.sessions.createIndex({ session_id: 1 }, { unique: true });
      db.sessions.createIndex({ player_id: 1, room: 1 });
      db.sessions.createIndex({ expires_at: 1 }, { expireAfterSeconds: 0 });
      db.rounds.createIndex({ room_id: 1, round_no: -1 }, { unique: true });
      db.bets.createIndex({ bet_id: 1 }, { unique: true });
      db.settlements.createIndex({ bet_id: 1 }, { unique: true });
      print("indexes created");
    ' || say "index creation failed — check the URL and permissions"
  else
    say "mongosh not installed; skipped. Indexes to create by hand:"
    say "  sessions: {session_id:1} unique, {expires_at:1} TTL 0"
    say "  rounds:    {room_id:1, round_no:-1} unique"
    say "  bets:      {bet_id:1} unique"
    say "  settlements: {bet_id:1} unique  (exactly-once payout)"
  fi
fi

# ------------------------------------------------------------------ verify
step "Verifying the API"
if curl -fsS --max-time 15 "$API/health" >/dev/null 2>&1; then
  say "API reachable: $API/health"
else
  say "could not reach $API/health"
  say "the .env is still correct; check the network and try again"
fi

if curl -fsS --max-time 15 -H "X-Admin-Key: $OP_KEY" \
     "$API/api/v1/admin/dashboard" >/dev/null 2>&1; then
  say "operator key accepted by /api/v1/admin/dashboard"
else
  say "the operator key was rejected by the admin API"
  say "check it with the operator who issued it"
fi

step "Done"
cat <<NEXTEOF
Next:
  1. Read .env — it holds your operator key and HMAC secret. Never commit it.
  2. Wire the scaffolded file into your app (see the comments in it).
  3. Mint a table link to try it:
       curl -sS -H "X-Admin-Key: \$OPERATOR_API_KEY" \\
            -H 'Content-Type: application/json' \\
            -d '{"player_id":"player_1","room":"teen-patti-low"}' \\
            "$API/api/v1/admin/sessions/mint"
  4. Full reference: $API/api-docs
NEXTEOF
